Skip loading data tables from temporary locations
This avoids (debug) messages like:

```
Cannot find index file '/data/users/mvandenb/gx124/tmp_nfs/jwd/tmp-toolshed-gmfcrszrHTL/all_fasta.loc' for tool data table 'all_fasta'
```

More importantly, when installing a new data table along with a repository this will prevent

```
IOError: [Errno 2] No such file or directory: '/data/users/mvandenb/gx/galaxy/tool-data/toolshed.g2.bx.psu.edu/repos/iuc/snpeff/698ef30638a8/snpeffv_genomedb.loc'
  File "galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "galaxy/webapps/galaxy/api/tool_shed_repositories.py", line 528, in install_repository_revision
    payload)
  File "tool_shed/galaxy_install/install_manager.py", line 706, in install
    install_options
  File "tool_shed/galaxy_install/install_manager.py", line 805, in __initiate_and_install_repositories
    return self.install_repositories(tsr_ids, decoded_kwd, reinstalling=False)
  File "tool_shed/galaxy_install/install_manager.py", line 852, in install_repositories
    tool_panel_section_mapping=tool_panel_section_mapping)
  File "tool_shed/galaxy_install/install_manager.py", line 902, in install_tool_shed_repository
    tool_panel_section_mapping=tool_panel_section_mapping)
  File "tool_shed/galaxy_install/install_manager.py", line 561, in __handle_repository_contents
    sample_files_copied)
  File "tool_shed/util/tool_util.py", line 179, in handle_missing_index_file
    options.tool_data_table.handle_found_index_file(options.missing_index_file)
  File "galaxy/tools/data/__init__.py", line 422, in handle_found_index_file
    self.extend_data_with(filename)
  File "galaxy/tools/data/__init__.py", line 488, in extend_data_with
    self.data.extend(self.parse_file_fields(open(filename), errors=errors, here=here))
```
which is due to `missing_index_file` pointing to the temporary loc file, that
doesn't exist anymore.